#!/usr/bin/env bash
# Seed default dotfiles into the persistent home on first run.
# .bashrc is always written as a thin shim that sources the image's bashrc.default
# (so image updates take effect immediately) plus ~/.bashrc.local for personal overrides.
# The shim is idempotent — overwritten on every start to stay current with the image.
# Put personal customizations in ~/.bashrc.local, not ~/.bashrc.
set -euo pipefail

SKEL=/etc/skel-devbox

# Always write .bashrc as a thin shim — image is authoritative for defaults.
cat > "$HOME/.bashrc" <<'EOF'
# ============================================================
# DO NOT EDIT THIS FILE — it is overwritten on every container
# start. Put your personal customizations in ~/.bashrc.local
# ============================================================

# Source image defaults (aliases, prompt, history settings, etc.)
[ -f /etc/skel-devbox/bashrc.default ] && . /etc/skel-devbox/bashrc.default

# Personal overrides — create this file for your own tweaks.
[ -f "$HOME/.bashrc.local" ] && . "$HOME/.bashrc.local"

# Run after personal overrides so mem-check thresholds can be customized there.
[ -f /usr/local/bin/mem-check ] && . /usr/local/bin/mem-check
EOF

# Seed .profile only if missing (less likely to need updates).
if [ ! -e "$HOME/.profile" ] && [ -f "$SKEL/profile.default" ]; then
    cp "$SKEL/profile.default" "$HOME/.profile"
fi

# Always write opencode tui.json — image is authoritative for TUI defaults.
mkdir -p "$HOME/.config/opencode"
cp "$SKEL/tui.json" "$HOME/.config/opencode/tui.json"

mkdir -p "$HOME/.local/bin" "$HOME/.config"
mkdir -p "$HOME/.ssh" && chmod 700 "$HOME/.ssh"

# Seed glab config only if missing — auth tokens get written back into this
# file by 'glab auth login', so we must not overwrite an existing file.
if [ ! -e "$HOME/.config/glab-cli/config.yml" ] && [ -f "$SKEL/glab-config.yml" ]; then
    mkdir -p "$HOME/.config/glab-cli"
    cp "$SKEL/glab-config.yml" "$HOME/.config/glab-cli/config.yml"
    chmod 600 "$HOME/.config/glab-cli/config.yml"
fi

# Seed ~/.ssh/config with a gitlab.cfdata.org stanza if not already present.
if ! grep -qF "gitlab.cfdata.org" "$HOME/.ssh/config" 2>/dev/null; then
    cat >> "$HOME/.ssh/config" <<'SSHCONF'
Host gitlab.cfdata.org
    IdentityFile ~/.ssh/id_ed25519_crate
    IdentitiesOnly yes
SSHCONF
    chmod 600 "$HOME/.ssh/config"
fi

# Generate a crate-specific SSH keypair on first run.
# Add the public key to your GitLab profile at gitlab.cfdata.org.
if [ ! -f "$HOME/.ssh/id_ed25519_crate" ]; then
    ssh-keygen -t ed25519 -C "crate@$(hostname)" -f "$HOME/.ssh/id_ed25519_crate" -N ""
    echo ""
    echo "================================================================"
    echo " New SSH key generated. Add this public key to GitLab:"
    echo " https://gitlab.cfdata.org/-/profile/keys"
    echo ""
    cat "$HOME/.ssh/id_ed25519_crate.pub"
    echo "================================================================"
    echo ""
fi

# Ensure gitlab.cfdata.org host key is in known_hosts. Scanned live so no
# keys are stored in the repo. -H hashes the hostname (standard hardening).
# Safe to run on every start — skipped if the sentinel file exists.
if [ ! -f "$HOME/.ssh/.known_hosts_gitlab_scanned" ]; then
    ssh-keyscan -H gitlab.cfdata.org >> "$HOME/.ssh/known_hosts" 2>/dev/null || true
    chmod 600 "$HOME/.ssh/known_hosts"
    touch "$HOME/.ssh/.known_hosts_gitlab_scanned"
fi

# Load the cron schedule from the mounted repo (if present) and start the
# cron daemon. Schedule lives outside the image (~/dev/cust/scripts/crontab)
# so tweaking timing doesn't require an image rebuild — only adding/removing
# the cron package itself does. Re-run on every start so edits take effect on
# container restart without needing a rebuild.
CRON_SRC="$HOME/dev/cust/scripts/crontab"
if [ -f "$CRON_SRC" ]; then
    crontab "$CRON_SRC"
    sudo service cron start || sudo service cron restart
fi

exec "$@"
