#!/usr/bin/env bash
# Seed default dotfiles into the persistent home on first run.
# .bashrc is always written as a thin shim that sources the image's bashrc.default
# (so image updates take effect immediately) plus ~/.bashrc.local for personal overrides.
# The shim is idempotent — overwritten on every start to stay current with the image.
# Put personal customizations in ~/.bashrc.local, not ~/.bashrc.
set -euo pipefail

SKEL=/etc/skel-devbox

# Always write .bashrc as a thin shim — image is authoritative for defaults.
cat > "$HOME/.bashrc" <<'EOF'
# ============================================================
# DO NOT EDIT THIS FILE — it is overwritten on every container
# start. Put your personal customizations in ~/.bashrc.local
# ============================================================

# Source image defaults (aliases, prompt, history settings, etc.)
[ -f /etc/skel-devbox/bashrc.default ] && . /etc/skel-devbox/bashrc.default

# Personal overrides — create this file for your own tweaks.
[ -f "$HOME/.bashrc.local" ] && . "$HOME/.bashrc.local"
EOF

# Seed .profile only if missing (less likely to need updates).
if [ ! -e "$HOME/.profile" ] && [ -f "$SKEL/profile.default" ]; then
    cp "$SKEL/profile.default" "$HOME/.profile"
fi

# Always write opencode tui.json — image is authoritative for TUI defaults.
mkdir -p "$HOME/.config/opencode"
cp "$SKEL/tui.json" "$HOME/.config/opencode/tui.json"

mkdir -p "$HOME/.local/bin" "$HOME/.config"
mkdir -p "$HOME/.ssh" && chmod 700 "$HOME/.ssh"

exec "$@"
