#!/usr/bin/env bash
# Generate ~/.config/ghostty/config so opening Ghostty attaches to the crate singleton container.
#
# Architecture: crate runs as a persistent singleton (started at login via launchd).
# Each Ghostty window runs `box`, which does `docker exec -it crate bash -l`.
# Multiple windows share the same container with no port conflicts.
#
# Prereq:  brew install --cask ghostty   (or install into ~/Applications via --appdir)
# Refuses to overwrite an existing config.
set -euo pipefail

cfg_dir="$HOME/.config/ghostty"
cfg_file="$cfg_dir/config"
script_dir="$(cd "$(dirname "$0")" && pwd)"
box_script="$script_dir/box"

if [ ! -x "$box_script" ]; then
    echo "ERROR: $box_script not found or not executable." >&2
    exit 1
fi

if [ -e "$cfg_file" ]; then
    echo "ERROR: $cfg_file already exists." >&2
    echo "Move or remove it first if you really want to regenerate." >&2
    exit 1
fi

# Locate Ghostty install for a friendlier confirmation message; not required to write the config.
ghostty_app=""
for p in /Applications/Ghostty.app "$HOME/Applications/Ghostty.app"; do
    [ -d "$p" ] && { ghostty_app="$p"; break; }
done

user=$(whoami)
mkdir -p "$cfg_dir"
cat > "$cfg_file" <<EOF
# Ghostty config — attaches to the crate singleton container.
# Each new Ghostty window/tab runs 'box', which does: docker exec -it crate bash -l
# Multiple windows share the same container — no port conflicts.
# Generated by setup-ghostty.sh on $(date -u +%FT%TZ) for host user '$user'.

command = $box_script

title = crate
font-size = 13
window-padding-x = 8
window-padding-y = 8

# Keep the window after the shell exits so any error stays visible.
# Set to false if you prefer the window to close instantly on exit.
wait-after-command = true

# Scrollback buffer — default is 10MB, bumped to 100MB for longer session history.
scrollback-limit = 104857600
EOF

echo "Wrote: $cfg_file"
echo "  box: $box_script"
echo "  ghostty: ${ghostty_app:-NOT INSTALLED — run: brew install --cask ghostty}"
echo ""
echo "Next steps:"
echo "  1. Install the launchd agent so crate starts at login:"
echo "       cp $script_dir/com.groutledge.crate.plist ~/Library/LaunchAgents/"
echo "       launchctl load -w ~/Library/LaunchAgents/com.groutledge.crate.plist"
echo "  2. Start the container now (or just open Ghostty — box will start it):"
echo "       cd $script_dir && docker compose up -d"
echo "  3. Open Ghostty. You should land at crate@crate:~\$"
echo ""
echo "IMPORTANT: if Ghostty is already running, Cmd-Q it fully (not just close the window)"
echo "           before reopening — running instances ignore config changes."
