#!/usr/bin/env bash
# Generate ~/.config/ghostty/config so opening Ghostty launches the crate container directly.
#
# Prereq:  brew install --cask ghostty   (or install into ~/Applications via --appdir)
# Refuses to overwrite an existing config.
set -euo pipefail

cfg_dir="$HOME/.config/ghostty"
cfg_file="$cfg_dir/config"

# Locate the docker binary. OrbStack first, then standard brew locations.
docker_path=""
for p in \
    /Applications/OrbStack.app/Contents/MacOS/xbin/docker \
    /usr/local/bin/docker \
    /opt/homebrew/bin/docker; do
    if [ -x "$p" ]; then
        docker_path="$p"
        break
    fi
done

if [ -z "$docker_path" ]; then
    echo "ERROR: could not find docker. Install OrbStack (or Docker Desktop) first." >&2
    exit 1
fi

if [ -e "$cfg_file" ]; then
    echo "ERROR: $cfg_file already exists." >&2
    echo "Move or remove it first if you really want to regenerate." >&2
    exit 1
fi

# Locate Ghostty install for a friendlier confirmation message; not required to write the config.
ghostty_app=""
for p in /Applications/Ghostty.app "$HOME/Applications/Ghostty.app"; do
    [ -d "$p" ] && { ghostty_app="$p"; break; }
done

user=$(whoami)
mkdir -p "$cfg_dir"
cat > "$cfg_file" <<EOF
# Ghostty config — dedicated to launching the crate container.
# Opening Ghostty drops you straight into a fresh container shell.
# Generated by setup-ghostty.sh on $(date -u +%FT%TZ) for host user '$user'.

# Absolute paths used so this works regardless of Ghostty's PATH inheritance from launchd.
# Container home is /home/$user — matches the image's USERNAME build-arg from crate-build.
command = $docker_path run --rm -it --init --hostname crate -v $HOME/docker-home:/home/$user -v $HOME/dev:/home/$user/dev -w /home/$user crate:latest

title = crate
font-size = 13
window-padding-x = 8
window-padding-y = 8

# Keep the window after the container exits so any error stays visible.
# Set to false if you prefer the window to close instantly on exit.
wait-after-command = true
EOF

echo "Wrote: $cfg_file"
echo "  docker:  $docker_path"
echo "  ghostty: ${ghostty_app:-NOT INSTALLED — run: brew install --cask ghostty}"
echo ""
echo "IMPORTANT: if Ghostty is already running, Cmd-Q it fully (not just close the window)"
echo "           before reopening — running instances ignore config changes."
echo ""
echo "Next: open Ghostty (Spotlight 'Ghostty'). You should land at $user@crate:~\$"
echo "If you see a docker error instead, make sure OrbStack is running."
